from collections.abc import Iterable
from typing import Protocol


class Connection(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class GenericDataMapper[T](Protocol):
    def save(self, entities: Iterable[T]) -> None: ...
    def update(self, entities: Iterable[T]) -> None: ...
    def delete(self, entities: Iterable[T]) -> None: ...
